// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_the_silence_of_the_cats = "CgkI2ZPGvagXEAIQDQ"; // <GPGSID>
        public const string achievement_perfect_game_ii = "CgkI2ZPGvagXEAIQEg"; // <GPGSID>
        public const string achievement_score_100000 = "CgkI2ZPGvagXEAIQBg"; // <GPGSID>
        public const string achievement_are_they_sleeping = "CgkI2ZPGvagXEAIQDg"; // <GPGSID>
        public const string achievement_meowmeow = "CgkI2ZPGvagXEAIQCg"; // <GPGSID>
        public const string achievement_please_stop = "CgkI2ZPGvagXEAIQDA"; // <GPGSID>
        public const string achievement_score_50000 = "CgkI2ZPGvagXEAIQBQ"; // <GPGSID>
        public const string achievement_perfect__game_i = "CgkI2ZPGvagXEAIQEQ"; // <GPGSID>
        public const string achievement_perfect_game_iii = "CgkI2ZPGvagXEAIQEw"; // <GPGSID>
        public const string leaderboard_ranking = "CgkI2ZPGvagXEAIQFg"; // <GPGSID>
        public const string achievement_meowmeowmeowmeow = "CgkI2ZPGvagXEAIQCw"; // <GPGSID>
        public const string achievement_thanks_for_playing = "CgkI2ZPGvagXEAIQFQ"; // <GPGSID>
        public const string achievement_lets_go_su = "CgkI2ZPGvagXEAIQDw"; // <GPGSID>
        public const string achievement_score_10000 = "CgkI2ZPGvagXEAIQAw"; // <GPGSID>
        public const string achievement_im_more_of_a_dog_person = "CgkI2ZPGvagXEAIQCA"; // <GPGSID>
        public const string achievement_lets_go_do = "CgkI2ZPGvagXEAIQEA"; // <GPGSID>
        public const string achievement_score_25000 = "CgkI2ZPGvagXEAIQBA"; // <GPGSID>
        public const string achievement_meow = "CgkI2ZPGvagXEAIQCQ"; // <GPGSID>
        public const string achievement_score_5000 = "CgkI2ZPGvagXEAIQAg"; // <GPGSID>
        public const string achievement_score_1000000 = "CgkI2ZPGvagXEAIQBw"; // <GPGSID>
        public const string achievement_hello_dosu = "CgkI2ZPGvagXEAIQFA"; // <GPGSID>

}

